version: '3'
services:

  rethinkdb:
    build: ./rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - ./db-data:/data 
    networks:
      testing_net:
        ipv4_address: 172.28.1.14

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
